mysql_link_demo = 'mysql+pymysql://root:123456@localhost:3306/clevering'  # mysql demo
redis_link_demo = 'redis://:@0.0.0.0:0/0'  # redis demo
Mysql_user = 'root'  # username
Mysql_pass = '123456'  # password
Mysql_addr = 'localhost:3306'  # mysql的address
Mysql_db = 'clevering'  # 数据库名称
NACOS_addr = ''  # nacos的address
NACOS_namespace = "dev"  # 命名空间，必须是dev
Redis_addr = '127.0.0.1'  # redis的address
Redis_pass = 'clevering'  # redis 密码
FILE_PATH_WIN = "C:/Clevering/CloudFiles/"  # WINDOWS文件目录前缀
FILE_PATH_MAC = "/Users/Clevering/CloudFiles/"  # MAC文件目录前缀
FILE_PATH_LINUX = "/home/Clevering/CloudFiles/"  # LINUX文件目录前缀
